name: intventory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.7
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  image_gallery_saver: ^2.0.3
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_charts: ^22.2.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - google_fonts/montserrat_alternates/
    - assets/images/
